# ros2 run mavros mavros_node --ros-args --params-file /svea_ws/src/svea_core/params/svea_mavros.yaml
/**:
  ros__parameters:
    fcu_url: "udp://:14551@host.docker.internal:14551"
    plugin_allowlist:
      - sys_status
      - sys_time
      - command
      - param
      - rc_io
      - imu
      - state
      - mavlink
      - setpoint_raw
